version: "3.4"

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: alpineair_phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    links:
      - db:mysql
    ports:
      - "8090:80"
    restart: unless-stopped
    depends_on:
      - db
      - app
      - nginx

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: alpineair/nginx:latest
    container_name: alpineair_webserver
    restart: unless-stopped
    tty: true
    environment:
      RUNNING_IN_DOCKER: 'true'
      WEB_LOCAL_URL: ${WEB_LOCAL_URL}
    ports:
      - '80:80'
      - '443:443'
      - '8888:80'
    volumes:
      - alpineair_app_data:${WEB_DESTINATION_PATH}
      - ${WEB_APP_PATH}${WEB_APP_PROJECT_PATH}/docker/nginx/default-site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: alpineair/php:latest
    container_name: alpineair_app
    restart: unless-stopped
    tty: true
    environment:
      RUNNING_IN_DOCKER: 'true'
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - alpineair_app_data:${WEB_DESTINATION_PATH}
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    image: alpineair/mysql:latest
    container_name: alpineair_db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      RUN_INIT_FILES: ${DOCKER_RUN_MYSQL_INIT}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ${WEB_APP_PATH}${WEB_APP_PROJECT_PATH}/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - alpineair_mysql_db:/var/lib/mysql

volumes:
  alpineair_app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WEB_APP_PATH}${WEB_APP_PROJECT_PATH}
  alpineair_mysql_db:
  portainer_data:

